version: '2'
services:

  nodered:
    build: ./nodered
    networks:
      - microservicesnet
    environment:
      - SERVICE_NAME=node-red
    ports:
      - "1880:1880"
    volumes:
      - ${PWD}/nodered/config:/root/.node-red
    links:
      - mosquitto

  homebridge:
    build: ./homebridge
    network_mode: host
    environment:
      - SERVICE_NAME=homebridge
    ports:
      - "5353:5353"
      - "51826:51826"
    volumes:
      - ${PWD}/homebridge/config:/root/.homebridge

  mosquitto:
    build: ./mosquitto
    networks:
      - microservicesnet
    environment:
      - SERVICE_NAME=mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

networks:
  microservicesnet:
    driver: bridge
