version: '3'
services:

  nodered:
    network_mode: host
    environment:
      - SERVICE_NAME=nodered
    volumes:
      - ./nodered:/root/.node-red
    depends_on:
      - mosquitto
      - homebridge

  homebridge:
    network_mode: host
    environment:
      - SERVICE_NAME=homebridge
    volumes:
      - ./homebridge:/root/.homebridge
    depends_on:
      - mosquitto

  mosquitto:
    network_mode: host
    environment:
      - SERVICE_NAME=mosquitto