version: '3'
services:

  nodered:
    build: ./nodered
    networks:
      - microservicesnet
    environment:
      - SERVICE_NAME=nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/config:/root/.nodered
    depends_on:
      - mosquitto
      - homebridge
    links:
      - mosquitto

  homebridge:
    build: ./homebridge
    network_mode: host
    environment:
      - SERVICE_NAME=homebridge
    ports:
      - "5353:5353"
      - "51826:51826"
    volumes:
      - ./homebridge/config:/root/.homebridge
    depends_on:
      - mosquitto

  mosquitto:
    build: ./mosquitto
    networks:
      - microservicesnet
    environment:
      - SERVICE_NAME=mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

networks:
  microservicesnet:
    driver: bridge
