version: '3'
services:
  nodered:
    image: ghcr.io/lafin/nodered
    network_mode: host
    environment:
      - SERVICE_NAME=nodered
    volumes:
      - ./nodered:/home/node/.node-red
    depends_on:
      - mosquitto
      - homebridge
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
  homebridge:
    image: oznu/homebridge:raspberry-pi
    network_mode: host
    environment:
      - SERVICE_NAME=homebridge
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./homebridge:/root/.homebridge
    depends_on:
      - mosquitto
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
  mosquitto:
    image: ghcr.io/lafin/mosquitto
    network_mode: host
    environment:
      - SERVICE_NAME=mosquitto
      - TZ
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - SERVICE_NAME=zigbee
      - TZ
    volumes:
      - ./zigbee:/app/data
    depends_on:
      - mosquitto
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
