version: '3'
services:

  consul:
    image:  gliderlabs/consul-server
    command: "-bootstrap -client 0.0.0.0"
    container_name: consul
    hostname: consul
    networks:
      - microservicesnet
    ports:
      - "8500:8500"

  registrator:
    image: gliderlabs/registrator
    command: "-internal consul://consul:8500"
    container_name: registrator
    hostname: registrator
    networks:
      - microservicesnet
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
