name: actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [nodered, homebridge, mosquitto]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.app }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/lafin/${{ matrix.app }}:latest
